-- =============================================================================
-- V2 : Rebuild schema to match current JPA entities
-- =============================================================================
-- V1 created tables that no longer match the entities
-- (wrong columns, outbox_events table not used, etc.).
-- This migration drops those and creates the real schema from scratch.
-- =============================================================================

       -- CASCADE drops FKs in dependent tables too


-- =============================================================================
-- USERS
-- Derived from: com.greatest.shortUrl.entity.User
-- =============================================================================
CREATE TABLE users (
    id          VARCHAR(36)  PRIMARY KEY,          -- UUID generated by JPA
    email       VARCHAR(100) NOT NULL UNIQUE,
    password    VARCHAR(100) NOT NULL,
    name        VARCHAR(100) NOT NULL,
    role        VARCHAR(20)  NOT NULL DEFAULT 'ROLE_USER',
    created_at  TIMESTAMPTZ  NOT NULL
);

CREATE INDEX idx_users_email ON users (email);


-- =============================================================================
-- SHORT_URLS
-- Derived from: com.greatest.shortUrl.entity.ShortUrl
-- =============================================================================
CREATE TABLE short_urls (
    id           VARCHAR(36)  PRIMARY KEY,          -- UUID generated by JPA
    short_key    VARCHAR(10)  NOT NULL UNIQUE,       -- unique constraint relied on by retry logic
    original_url TEXT         NOT NULL,
    is_private   BOOLEAN      NOT NULL DEFAULT FALSE,
    expires_at   TIMESTAMPTZ,
    created_by   VARCHAR(36)  REFERENCES users(id) ON DELETE SET NULL,
    click_count  BIGINT       NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ  NOT NULL,
    status       VARCHAR(20)  NOT NULL               -- ACTIVE | EXPIRED | DELETED
);

-- Indexes from @Table(indexes = {...}) in ShortUrl entity
CREATE INDEX idx_short_key   ON short_urls (short_key);
CREATE INDEX idx_created_by  ON short_urls (created_by);
CREATE INDEX idx_status       ON short_urls (status);
CREATE INDEX idx_expires_at  ON short_urls (expires_at);

-- Partial index: fast lookup for the scheduled expiry job
-- "WHERE status = 'ACTIVE' AND expires_at < NOW()"
CREATE INDEX idx_active_expires ON short_urls (expires_at)
    WHERE status = 'ACTIVE' AND expires_at IS NOT NULL;


-- =============================================================================
-- TOKENS  (refresh tokens)
-- Derived from: com.greatest.shortUrl.entity.RefreshToken
-- =============================================================================
CREATE TABLE tokens (
    id           BIGSERIAL    PRIMARY KEY,           -- IDENTITY strategy -> BIGSERIAL
    token        TEXT         NOT NULL UNIQUE,
    expiry_date  TIMESTAMPTZ  NOT NULL,
    user_id      VARCHAR(36)  REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_tokens_user_id ON tokens (user_id);


-- =============================================================================
-- PASSWORD_RESET_TOKENS
-- Derived from: com.greatest.shortUrl.entity.PasswordResetToken
-- =============================================================================
CREATE TABLE password_reset_tokens (
    id          VARCHAR(36)  PRIMARY KEY,            -- UUID generated by JPA
    token       TEXT         NOT NULL UNIQUE,
    user_id     VARCHAR(36)  REFERENCES users(id) ON DELETE CASCADE,
    expires_at  TIMESTAMPTZ  NOT NULL,
    used        BOOLEAN      NOT NULL DEFAULT FALSE
);

-- Fast lookup: AuthService does findByToken()
CREATE INDEX idx_prt_token   ON password_reset_tokens (token);
CREATE INDEX idx_prt_user_id ON password_reset_tokens (user_id);
